# Generated by Django 3.1.4 on 2020-12-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
